# fly.toml app configuration file generated for beth-b2big on 2023-10-22T18:34:21-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beth-b2big"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
